# Generated by Django 4.0.6 on 2022-07-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crimes2001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseno', models.CharField(max_length=20)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('block', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Type_desc', models.CharField(max_length=100)),
                ('Where', models.CharField(max_length=100)),
                ('Arrest', models.BooleanField()),
                ('Domestic', models.BooleanField()),
                ('District', models.IntegerField()),
                ('Community_area', models.FloatField(null=True)),
                ('Year', models.IntegerField()),
                ('Latitude', models.FloatField(max_length=20, null=True)),
                ('Longitude', models.FloatField(max_length=20, null=True)),
            ],
        ),
    ]
