# Generated by Django 4.0.6 on 2022-07-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeMapping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='', max_length=50)),
                ('last_name', models.TextField(default='', max_length=50)),
                ('User_email', models.EmailField(default='', max_length=50)),
                ('User_subject', models.TextField(default='', max_length=100)),
                ('User_message', models.TextField(default='', max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
