# Generated by Django 4.0.6 on 2022-07-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeMapping', '0002_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='User_subject',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
