# Generated by Django 4.0.6 on 2022-08-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeMapping', '0004_graphdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DISTRICT', models.IntegerField()),
                ('DISNAME', models.CharField(max_length=100)),
                ('ADDRESS', models.CharField(max_length=100)),
                ('CITY', models.CharField(max_length=100)),
                ('ZIP', models.IntegerField()),
                ('WEBSITE', models.CharField(max_length=500)),
                ('LATITUDE', models.FloatField(max_length=20, null=True)),
                ('LONGITUDE', models.FloatField(max_length=20, null=True)),
            ],
        ),
    ]
