# Generated by Django 4.0.6 on 2022-08-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeMapping', '0005_policestationlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policestationlist',
            old_name='ADDRESS',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='policestationlist',
            old_name='CITY',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='policestationlist',
            old_name='DISNAME',
            new_name='disname',
        ),
        migrations.RenameField(
            model_name='policestationlist',
            old_name='DISTRICT',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='policestationlist',
            old_name='LATITUDE',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='policestationlist',
            old_name='LONGITUDE',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='policestationlist',
            old_name='WEBSITE',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='policestationlist',
            old_name='ZIP',
            new_name='zip',
        ),
    ]
