# Generated by Django 4.0.6 on 2022-08-14 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeMapping', '0006_rename_address_policestationlist_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestationlist',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
