# Generated by Django 4.0.6 on 2022-08-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeMapping', '0007_policestationlist_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphdata',
            name='code',
        ),
        migrations.AddField(
            model_name='graphdata',
            name='Arrest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graphdata',
            name='District',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='graphdata',
            name='Domestic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graphdata',
            name='Type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='graphdata',
            name='Type_desc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='graphdata',
            name='Where',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='graphdata',
            name='Year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='graphdata',
            name='block',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
