# Generated by Django 4.0.5 on 2022-09-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeMapping', '0010_rename_year_graphdata_yeare_graphdata_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='ukdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseno', models.CharField(max_length=20)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('block', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Type_desc', models.CharField(max_length=100)),
                ('Where', models.CharField(max_length=100)),
                ('Arrest', models.BooleanField()),
                ('Domestic', models.BooleanField()),
                ('District', models.IntegerField()),
                ('Community_area', models.FloatField(null=True)),
                ('Year', models.IntegerField()),
                ('Latitude', models.FloatField(max_length=20, null=True)),
                ('Longitude', models.FloatField(max_length=20, null=True)),
                ('IPC', models.FloatField(max_length=20, null=True)),
                ('Session', models.CharField(max_length=20, null=True)),
                ('Day', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='Type',
            field=models.TextField(blank=True, choices=[('ARSON', 'ARSON'), ('ASSAULT', 'ASSAULT'), ('ASSUALT', 'ASSUALT'), ('BATTERY', 'BATTERY'), ('BURGLARY', 'BURGLARY'), ('CONCEALED CARRY LICENSE VIOLATION', 'CONCEALED CARRY LICENSE VIOLATION'), ('CRIM SEXUAL ASSAULT', 'CRIM SEXUAL ASSAULT'), ('CRIMINAL DAMAGE', 'CRIMINAL DAMAGE'), ('CRIMINAL SEXUAL ASSAULT', 'CRIMINAL SEXUAL ASSAULT'), ('CRIMINAL TRESPASS', 'CRIMINAL TRESPASS'), ('DECEPTIVE PRACTICE', 'DECEPTIVE PRACTICE'), ('GAMBLING', 'GAMBLING'), ('HOMICIDE', 'HOMICIDE'), ('HUMAN TRAFFICKING', 'HUMAN TRAFFICKING'), ('INTERFERENCE WITH PUBLIC OFFICER', 'INTERFERENCE WITH PUBLIC OFFICER'), ('INTIMIDATION', 'INTIMIDATION'), ('KIDNAPPING', 'KIDNAPPING'), ('LIQUOR LAW VIOLATION', 'LIQUOR LAW VIOLATION'), ('MOTOR VEHICLE नशीले पदार्थों', 'MOTOR VEHICLE नशीले पदार्थों'), ('NARCOTICS', 'NARCOTICS'), ('NON - CRIMINAL', 'NON - CRIMINAL'), ('OBSCENITY', 'OBSCENITY'), ('OFFENSE INVOLVING CHILDREN', 'OFFENSE INVOLVING CHILDREN'), ('OTHER OFFENSE', 'OTHER OFFENSE'), ('PROSTITUTION', 'PROSTITUTION'), ('PUBLIC PEACE VIOLATION', 'PUBLIC PEACE VIOLATION'), ('ROBBERY', 'ROBBERY'), ('SEX OFFENSE', 'SEX OFFENSE'), ('STALKING', 'STALKING'), ('Theft', 'Theft'), ('WEAPONS VIOLATION', 'WEAPONS VIOLATION'), ('नशीले पदार्थों', 'नशीले पदार्थों')], null=True),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='YearE',
            field=models.IntegerField(blank=True, choices=[(2001, 2001), (2002, 2002), (2003, 2003), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2022, 2022)], null=True),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='YearS',
            field=models.IntegerField(blank=True, choices=[(2001, 2001), (2002, 2002), (2003, 2003), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2022, 2022)], null=True),
        ),
    ]
