# Generated by Django 4.0.5 on 2022-09-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeMapping', '0013_ukdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ukdata',
            name='IPC',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
