# Generated by Django 4.0.6 on 2023-12-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeMapping', '0017_firdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RajPolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(null=True)),
                ('latitude', models.FloatField(max_length=20, null=True)),
                ('longitude', models.FloatField(max_length=20, null=True)),
            ],
        ),
    ]
