# Generated by Django 4.0.6 on 2024-01-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeMapping', '0018_rajpolice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authenticate',
        ),
        migrations.RenameField(
            model_name='firdata',
            old_name='office_Address',
            new_name='office_address',
        ),
        migrations.AddField(
            model_name='firdata',
            name='ipc_no',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='firdata',
            name='police_station',
            field=models.TextField(null=True),
        ),
    ]
