# Generated by Django 4.0.6 on 2024-01-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeMapping', '0019_delete_authenticate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firdata',
            name='language',
            field=models.TextField(null=True),
        ),
    ]
