# Generated by Django 4.0.6 on 2024-01-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeMapping', '0020_firdata_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='firdata',
            name='bailable',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='firdata',
            name='cognizable',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='firdata',
            name='court',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='firdata',
            name='offence',
            field=models.TextField(null=True),
        ),
    ]
