# Generated by Django 4.0.6 on 2024-01-16 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeMapping', '0021_firdata_bailable_firdata_cognizable_firdata_court_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firdata',
            name='bailable',
        ),
        migrations.RemoveField(
            model_name='firdata',
            name='cognizable',
        ),
        migrations.RemoveField(
            model_name='firdata',
            name='court',
        ),
        migrations.RemoveField(
            model_name='firdata',
            name='offence',
        ),
    ]
