# Generated by Django 4.0.6 on 2024-01-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeMapping', '0022_remove_firdata_bailable_remove_firdata_cognizable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firdata',
            name='location',
        ),
    ]
