# Generated by Django 4.0.6 on 2024-01-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeMapping', '0022_remove_firdata_bailable_remove_firdata_cognizable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStationJaipurList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Police_Station', models.TextField(null=True)),
                ('Phone_Number', models.TextField(null=True)),
                ('Address', models.TextField(null=True)),
                ('Latitude', models.FloatField(max_length=20, null=True)),
                ('Longitude', models.FloatField(max_length=20, null=True)),
            ],
        ),
    ]
