# Generated by Django 4.0.6 on 2024-01-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeMapping', '0023_remove_firdata_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='firdata',
            name='latitude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firdata',
            name='longitude',
            field=models.TextField(blank=True, null=True),
        ),
    ]
