# Generated by Django 4.0.6 on 2024-01-16 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeMapping', '0023_policestationjaipurlist'),
        ('CrimeMapping', '0024_firdata_latitude_firdata_longitude'),
    ]

    operations = [
    ]
