# Generated by Django 4.0.6 on 2024-04-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeMapping', '0027_mobdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_Name', models.CharField(max_length=255, null=True)),
                ('UnitName', models.CharField(max_length=255, null=True)),
                ('PoliceName', models.CharField(max_length=255, null=True)),
                ('Rank', models.CharField(max_length=255, null=True)),
                ('PoliceStation', models.CharField(max_length=255, null=True)),
                ('DateOfBirth', models.CharField(max_length=255, null=True)),
                ('Age', models.IntegerField(null=True)),
            ],
        ),
    ]
