from django.db import models

# STYLE_CHOICES = sorted([(item, item) for item in get_all_styles()])

# Create your models here.
class Crimes2001(models.Model):
    caseno = models.CharField(max_length=20)
    Date = models.DateTimeField(auto_now_add=True)
    block = models.CharField(max_length=100)
    Type = models.CharField(max_length=100)
    Type_desc = models.CharField(max_length=100)
    Where = models.CharField(max_length=100)
    Arrest = models.BooleanField()
    Domestic = models.BooleanField()
    District = models.IntegerField()
    Community_area = models.FloatField(null=True)
    Year = models.IntegerField()
    Latitude = models.FloatField(max_length=20, null=True)
    Longitude = models.FloatField(max_length=20, null=True)
    # IPC = models.CharField(max_length=20)	
    
# district,disname,address,city,zip,website,latitude,longitude
class PoliceStationList(models.Model):
    Date = models.DateTimeField(auto_now_add=True)
    district = models.IntegerField()
    disname = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    zip = models.IntegerField()
    website = models.CharField(max_length=500)
    latitude = models.FloatField(max_length=20, null=True)
    longitude = models.FloatField(max_length=20, null=True)
    
# UTTRAKHAND POLICE DATA district,disname,address,city,zip,website,latitude,longitude
class UKPoliceStationList(models.Model):
    Date = models.DateTimeField(auto_now_add=True)
    district = models.IntegerField()
    disname = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    zip = models.IntegerField()
    website = models.CharField(max_length=500)
    latitude = models.FloatField(max_length=20, null=True)
    longitude = models.FloatField(max_length=20, null=True)    
    
class ContactUs(models.Model):
    first_name = models.CharField(max_length=50,default='')
    last_name = models.CharField(max_length=50,default='')
    User_email = models.EmailField( max_length=50,default='')
    User_subject = models.CharField(max_length=100,default='')
    User_message = models.TextField( max_length=1000,default='')
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.User_email

# Uttrakhand data
class ukdata(models.Model):
    caseno = models.CharField(max_length=20)
    Date = models.DateTimeField(auto_now_add=True)
    block = models.CharField(max_length=100)
    Type = models.CharField(max_length=100)
    Type_desc = models.CharField(max_length=100)
    Where = models.CharField(max_length=100)
    Arrest = models.BooleanField()
    Domestic = models.BooleanField()
    District = models.IntegerField()
    Community_area = models.FloatField(null=True)
    Year = models.IntegerField()
    Latitude = models.FloatField(max_length=20, null=True)
    Longitude = models.FloatField(max_length=20, null=True)
    IPC = models.CharField(max_length=20, null=True)
    Session = models.CharField(max_length=20, null=True)
    Day = models.CharField(max_length=20, null=True)

    
getAll = Crimes2001.objects.all()

AllYear = list(getAll.values_list('Year',flat=True).distinct())
TupleYear = sorted([(item, item) for item in AllYear])

AllType = list(getAll.values_list('Type',flat=True).distinct())
TupleType = sorted([(item, item) for item in AllType])

AllBlock = list(getAll.values_list('block',flat=True).distinct())
TupleBlock = sorted([(item, item) for item in AllBlock])

AllWhere = list(getAll.values_list('Where',flat=True).distinct())
TupleWhere = sorted([(item, item) for item in AllWhere])

AllDistrict = list(getAll.values_list('District',flat=True).distinct())
TupleDistrict = sorted([(item, item) for item in AllDistrict])

class GraphData(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    title = models.TextField(null=True)
    Type = models.TextField(choices=TupleType, blank=True, null=True)
    Where = models.TextField(choices=TupleWhere, blank=True, null=True)
    Arrest = models.BooleanField(default=False)
    Domestic = models.BooleanField(default=False)
    District = models.IntegerField(choices=TupleDistrict, blank=True, null=True)
    YearS = models.IntegerField(choices=TupleYear, blank=True, null=True)
    YearE = models.IntegerField(choices=TupleYear, blank=True, null=True)

class FirData(models.Model):
    case_no	= models.TextField(null=True)
    date = models.TextField(null=True)
    police_station = models.TextField(null=True)
    ipc	= models.TextField(null=True)
    ipc_no = models.TextField(null=True)
    time =models.TextField(null=True)
    CrPC = models.TextField(null=True)	
    date_happened = models.TextField(null=True)
    date_reported= models.TextField(null=True)
    format_fir_type= models.TextField(null=True)
    address	= models.TextField(null=True)
    distance_police_station	= models.TextField(null=True)
    name= models.TextField(null=True)
    father_name	= models.TextField(null=True)
    age	= models.TextField(null=True)
    nationality	= models.TextField(null=True)
    office_address= models.TextField(null=True)
    additional_info	= models.TextField(null=True)
    suspected_individual = models.TextField(null=True)	
    latitude = models.TextField(null=True, blank=True)
    longitude = models.TextField(null=True, blank=True)
    file = models.URLField(max_length=200)
    language = models.TextField(null=True)

class RajPolice(models.Model):
    address=models.TextField(null=True)
    latitude=models.FloatField(max_length=20, null=True)
    longitude=models.FloatField(max_length=20, null=True)


class PoliceStationJaipurList(models.Model):
    Police_Station=models.TextField(null=True)
    Phone_Number=models.TextField(null=True)
    Address=models.TextField(null=True)
    Latitude=models.FloatField(max_length=20, null=True)
    Longitude=models.FloatField(max_length=20, null=True)



class FirKarnataka(models.Model):
    District_Name = models.CharField(max_length=255, null=True)
    UnitName = models.CharField(max_length=255, null=True)
    FIRNo = models.CharField(max_length=255, null=True)
    RI = models.IntegerField(null=True)
    Year = models.IntegerField(null=True)
    Month = models.IntegerField(null=True)
    Offence_From_Date = models.CharField(max_length=255, null=True)
    Offence_To_Date = models.CharField(max_length=255, null=True)
    FIR_Reg_DateTime = models.CharField(max_length=255, null=True)
    FIR_Date = models.CharField(max_length=255, null=True)
    FIR_Type = models.CharField(max_length=255, null=True)
    FIR_Stage = models.CharField(max_length=255, null=True)
    Complaint_Mode = models.CharField(max_length=255, null=True)
    CrimeGroup_Name = models.CharField(max_length=255, null=True)
    CrimeHead_Name = models.CharField(max_length=255, null=True)
    Latitude = models.FloatField(null=True)
    Longitude = models.FloatField(null=True)
    ActSection = models.CharField(max_length=255, null=True)
    IOName = models.CharField(max_length=255, null=True)
    KGID = models.CharField(max_length=255, null=True)
    Internal_IO = models.IntegerField(null=True)
    Place_of_Offence = models.CharField(max_length=255, null=True)
    Distance_from_PS = models.CharField(max_length=255, null=True)
    Beat_Name = models.CharField(max_length=255, null=True)
    Village_Area_Name = models.CharField(max_length=255, null=True)
    Male = models.IntegerField(null=True)
    Female = models.IntegerField(null=True)
    Boy = models.IntegerField(null=True)
    Girl = models.IntegerField(null=True)
    Age_0 = models.IntegerField(null=True)
    VICTIM_COUNT = models.IntegerField(null=True)
    Accused_Count = models.IntegerField(null=True)
    Arrested_Male = models.IntegerField(null=True)
    Arrested_Female = models.IntegerField(null=True)
    Arrested_Count = models.IntegerField(null=True)
    Accused_ChargeSheeted_Count = models.IntegerField(null=True)
    Conviction_Count = models.IntegerField(null=True)
    FIR_ID = models.IntegerField(null=True)
    Unit_ID = models.IntegerField(null=True)
    Crime_No = models.IntegerField(null=True)


class VictimInfo(models.Model):
    District_Name = models.CharField(max_length=255, null=True)
    UnitName = models.CharField(max_length=255, null=True)
    FIRNo = models.CharField(max_length=255, null=True)
    Year = models.IntegerField(null=True)
    Month = models.IntegerField(null=True)
    VictimName = models.CharField(max_length=255, null=True)
    age = models.IntegerField(null=True)
    Caste = models.CharField(max_length=255, null=True)
    Profession = models.CharField(max_length=255, null=True)
    Sex = models.CharField(max_length=255, null=True)
    PresentAddress = models.CharField(max_length=255, null=True)
    PresentCity = models.CharField(max_length=255, null=True)
    PresentState = models.CharField(max_length=255, null=True)
    PermanentAddress = models.CharField(max_length=255, null=True)
    PermanentCity = models.CharField(max_length=255, null=True)
    PermanentState = models.CharField(max_length=255, null=True)
    Nationality_Name = models.CharField(max_length=255, null=True)
    DOB = models.CharField(max_length=255, null=True)
    PersonType = models.CharField(max_length=255, null=True)
    InjuryType = models.CharField(max_length=255, null=True)
    Injury_Nature = models.CharField(max_length=255, null=True)
    Crime_No = models.IntegerField(null=True)
    Arr_ID = models.IntegerField(null=True)
    Victim_ID = models.IntegerField(null=True)


class MOBDetails(models.Model):
    District_Name = models.CharField(max_length=255, null=True)
    Unit_Name = models.CharField(max_length=255, null=True)
    Name = models.CharField(max_length=255, null=True)
    Person_No = models.CharField(max_length=255, null=True)
    MOB_Number = models.CharField(max_length=255, null=True)
    MobOpenDate = models.CharField(max_length=255, null=True)
    MOB_Open_Year = models.FloatField(null=True)
    Arrested_By = models.CharField(max_length=255, null=True)
    KGID = models.CharField(max_length=255, null=True)
    Caste = models.CharField(max_length=255, null=True)
    Grading = models.FloatField(null=True)
    Occupation = models.CharField(max_length=255, null=True)
    PS_Native = models.CharField(max_length=255, null=True)
    PS_District = models.CharField(max_length=255, null=True)
    Offender_Class = models.FloatField(null=True)
    Crime_No = models.CharField(max_length=255, null=True)
    ActSection = models.CharField(max_length=255, null=True)
    Brief_Fact = models.CharField(max_length=255, null=True)
    Present_WhereAbouts = models.CharField(max_length=255, null=True)
    Gang_Strength = models.IntegerField(null=True)
    Ident_Officer = models.CharField(max_length=255, null=True)
    officer_rank = models.CharField(max_length=255, null=True)
    Crime_Group1 = models.CharField(max_length=255, null=True)
    Crime_Head2 = models.CharField(max_length=255, null=True)
    class1 = models.CharField(max_length=255, null=True)
    AGE = models.FloatField(null=True)
    PresentAge = models.CharField(max_length=255, null=True)
    DOB = models.CharField(max_length=255, null=True)
    Address = models.CharField(max_length=255, null=True)
    SEX = models.CharField(max_length=255, null=True)
    Locality = models.CharField(max_length=255, null=True)
    LastUpdatedDate = models.CharField(max_length=255, null=True)

class RowdyShetters(models.Model):
    District_Name = models.CharField(max_length=255, null=True)
    Unit_Name = models.CharField(max_length=255, null=True)
    Rowdy_Sheet_No = models.IntegerField(null=True)
    Name = models.CharField(max_length=255, null=True)
    AliasName = models.CharField(max_length=255, null=True)
    RS_Open_Date = models.CharField(max_length=255, null=True)
    Rowdy_Classification_Details = models.CharField(max_length=255, null=True)
    Activities_Description = models.CharField(max_length=255, null=True)
    Rowdy_Category = models.IntegerField(null=True)
    PrevCase_Details = models.CharField(max_length=255, null=True)
    Address = models.CharField(max_length=255, null=True)
    Age = models.IntegerField(null=True)
    Father_Name = models.CharField(max_length=255, null=True)
    Source_Of_Income = models.CharField(max_length=255, null=True)
    LastUpdatedDate = models.CharField(max_length=255, null=True)
    PresentWhereabout = models.CharField(max_length=255, null=True)



class ComplainantsDetails(models.Model):
    District_Name = models.CharField(max_length=255, null=True)
    UnitName = models.CharField(max_length=255, null=True)
    FIRNo = models.CharField(max_length=255, null=True)
    Year = models.IntegerField(null=True)
    Month = models.IntegerField(null=True)
    ComplainantName = models.CharField(max_length=255, null=True)
    Relation = models.CharField(max_length=255, null=True)
    RelationshipName = models.CharField(max_length=255, null=True)
    DateOfBirth = models.CharField(max_length=255, null=True)
    Age = models.IntegerField(null=True)
    Sex = models.CharField(max_length=255, null=True)
    Nationality = models.CharField(max_length=255, null=True)
    Occupation = models.CharField(max_length=255, null=True)
    Address = models.CharField(max_length=255, null=True)
    City = models.CharField(max_length=255, null=True)
    State = models.CharField(max_length=255, null=True)
    Pincode = models.FloatField(null=True)
    Caste = models.CharField(max_length=255, null=True)
    Religion = models.CharField(max_length=255, null=True)
    FIR_ID = models.IntegerField(null=True)
    Unit_ID = models.IntegerField(null=True)
    Complaint_ID = models.IntegerField(null=True)



class PoliceDetails(models.Model):
    District_Name = models.CharField(max_length=255, null=True)
    UnitName = models.CharField(max_length=255, null=True)
    PoliceName = models.CharField(max_length=255, null=True)
    Rank = models.CharField(max_length=255, null=True)
    PoliceStation = models.CharField(max_length=255, null=True)
    DateOfBirth = models.CharField(max_length=255, null=True)
    Age = models.IntegerField(null=True)
